# Generated by Django 4.0.1 on 2023-02-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='basket_id',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='basket_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
