# Generated by Django 4.1.4 on 2023-01-24 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='recipes')),
                ('name', models.TextField()),
                ('author', models.TextField()),
                ('ingredients', models.TextField()),
                ('serving_size', models.IntegerField(default=0)),
                ('prep_time', models.IntegerField(default=0)),
                ('cook_time', models.IntegerField(default=0)),
                ('desc', models.TextField()),
                ('method', models.TextField()),
                ('notes', models.TextField(null=True)),
                ('calories', models.IntegerField(default=0)),
                ('allergens', models.TextField(null=True)),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rating', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='meals')),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('calories', models.IntegerField(default=0)),
                ('allergens', models.TextField(null=True)),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('special', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('manu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcumunch.menu')),
            ],
        ),
        migrations.CreateModel(
            name='FoodEaten',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ordered', models.IntegerField(null=True)),
                ('eaten', models.IntegerField(null=True)),
                ('recipe', models.IntegerField(null=True)),
                ('count', models.IntegerField(default=0)),
                ('meal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcumunch.meal')),
                ('recipe_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcumunch.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reg', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='user_images')),
                ('sex', models.TextField(max_length=1, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('height', models.IntegerField(default=0, null=True)),
                ('activity_level', models.IntegerField(default=0, null=True)),
                ('dietary_req', models.TextField(null=True)),
                ('preferences', models.TextField(null=True)),
                ('main_calories', models.IntegerField(default=0, null=True)),
                ('remain_calories', models.IntegerField(default=0, null=True)),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('acc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
