# Generated by Django 4.1.4 on 2023-02-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcumunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='user_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_rank',
            field=models.IntegerField(default=0),
        ),
    ]
