# Generated by Django 4.1.4 on 2023-02-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcumunch', '0002_meal_user_rank_recipe_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activity_level',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, null=True),
        ),
    ]
