# Generated by Django 4.1.4 on 2023-02-08 20:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dcumunch', '0003_alter_account_activity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activity_level',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='dietary_req',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Cereals containing gluten'), (2, 'Crustaceans'), (3, 'Eggs'), (4, 'Fish'), (5, 'Peanuts'), (6, ' Soybeans'), (7, 'Milk (Lactose)'), (8, 'Nuts'), (9, 'Celery'), (10, 'Mustard'), (11, 'Sesame seeds'), (12, 'Sulphur dioxide and sulphites'), (13, 'Lupin'), (14, 'Molluscs'), (15, 'Pork'), (16, 'Beef')], max_length=100, null=True),
        ),
    ]
