# Generated by Django 4.1.4 on 2023-02-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcumunch', '0006_alter_meal_allergens_alter_recipe_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
