# Generated by Django 4.1.4 on 2023-02-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcumunch', '0007_account_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='munched',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='ordered',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='munched',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='FoodEaten',
        ),
    ]
