# Generated by Django 4.1.4 on 2023-02-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcumunch', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ordered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
