# Generated by Django 4.1.4 on 2023-02-16 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcumunch', '0011_meal_liked_recipe_liked_likerecipe_likemeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='manu_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dcumunch.menu'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
