# Generated by Django 4.1.4 on 2023-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcumunch', '0012_alter_meal_desc_alter_meal_manu_id_alter_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ordered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='munched',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
