# Generated by Django 4.1.4 on 2023-02-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcumunch', '0010_meal_ordered'),
        ('dcumunch', '0013_alter_meal_ordered_alter_recipe_munched'),
    ]

    operations = [
    ]
