# Generated by Django 4.1.4 on 2023-02-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcumunch', '0016_alter_munchbasketitem_basket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='remain_carbs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='remain_fats',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='remain_protein',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
